package:
  name: conda-devsummit-2017-talk
  version: "1.0"

build:
  number: 0

source:
  git_rev: HEAD
  git_url: https://github.com/scw/conda-devsummit-2017-talk.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - scikit-learn

about:
  home: https://github.com/scw/conda-devsummit-2017-talk
  license: Apache
